# Generated by Django 4.0.6 on 2022-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0002_remove_projectdetail_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='booking_amount',
            field=models.IntegerField(blank=True, help_text='Enter remaing amount', null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='enter_amount',
            field=models.IntegerField(blank=True, help_text='Enter remaing amount', null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='total_paid',
            field=models.IntegerField(blank=True, help_text='Enter Total Paid Amount (in ₹)', null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='total_project_value',
            field=models.IntegerField(blank=True, help_text='Enter remaing amount', null=True),
        ),
    ]
