# Generated by Django 4.0.6 on 2022-07-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0004_alter_paymentinstallment_booking_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter remaing amount', max_digits=10, null=True),
        ),
    ]
