# Generated by Django 4.0.6 on 2022-07-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0005_paymentinstallment_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter remaing amount', max_digits=12, null=True),
        ),
    ]
