# Generated by Django 4.0.6 on 2022-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0006_alter_paymentinstallment_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
