# Generated by Django 4.0.6 on 2022-07-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0007_alter_registration_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='remaining_amount',
        ),
    ]
