# Generated by Django 4.0.6 on 2022-07-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0008_remove_paymentinstallment_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='booking_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Enter remaing amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='enter_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Enter remaing amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Enter Total Paid Amount (in ₹)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='total_project_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Enter remaing amount', max_digits=10, null=True),
        ),
    ]
