# Generated by Django 4.0.6 on 2022-07-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tki', '0009_alter_paymentinstallment_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='enter_amount',
            field=models.FloatField(blank=True, default=0, help_text='Enter remaing amount', null=True),
        ),
    ]
